### ISSUE TITLE
Can't get it to work with normal maps

### ISSUE THREAD

**Issue by stybbe** [Dsphar/Cube_Texture_Auto_Repeat_Unity#1]
Is repeat with normal map not supported or am I doing something wrong?

**Comment by stybbe** [comment]
It's not implemented. I found the solution and it was to repeat the normal texture, just like you did for mainTexture.

Following line solved it for me:

GetComponent<Renderer>().sharedMaterial.GetTexture(41).wrapMode = TextureWrapMode.Repeat;

**Comment by Dsphar** [comment]
That code contains nothing for normal maps. To be honest I have not gotten
that far in 3D rendering yet. When I learn run-time manipulation of normal
maps I will update the code, but that will not be for a while. Sorry.

On Mon, Apr 6, 2015 at 3:37 PM, stybbe <notifications@github.com> wrote:

> Is repeat with normal map not supported or am I doing something wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dsphar/Cube_Texture_Auto_Repeat_Unity/issues/1>.
>



-- 
Thanks,

David Sphar
(435) 740-1614 (call or text)
